### ISSUE TITLE
Double mutex unlock in nopoll_ctx_unregister_conn()

### ISSUE THREAD

**Issue by softins** [ASPLes/nopoll#21]
In `nopoll_ctx_unregister_conn()`, line 333 there is a call to `nopoll_mutex_unlock (ctx->ref_mutex)`, followed soon by a `break;`. The loop being exited is followed by another call to `nopoll_mutex_unlock`, which will result in a double-unlock.

Should the `break;` be a `return;` instead?

**Comment by francisbrosnan** [comment]
Hi Tony,

Thanks for taking your time for reviewing this and reporting. Certainly, you are right. That should be a "return;", otherwise it will cause another call to nopoll_mutex_unlock.

Applied patch: https://github.com/ASPLes/nopoll/commit/31c6ec4d7a68b06beda0dffcc4136b56a4adcb84

Thanks Tony,
Best Regards,
