### ISSUE TITLE
About use -lssl

### ISSUE THREAD

**Issue by Shaco-Ma** [ASPLes/nopoll#32]
@francisbrosnan 
Hi:
   Man, you configure have some question,Or I use wrong,like this:
   ./autogen.sh --host=$(CROSS_HOST) --enable-shared \
  --prefix=$(NOPOLL_SRC_DIR)/$(NOPOLL_LIB_DIR)  \
  LDFLAGS=-L/home/shaco/Work/ak_3918e_v200/platform/rootfs/rootfs_dana/usr/lib \
  CFLAGS=-I/home/shaco/Work/ak_3918e_v200/platform/rootfs/rootfs_dana/usr/include LIBS=-lcrypto;

  If I didn't add "LIBS=-lcrypto", the configure can't find ssl, and not support ssl, like this
   OpenSSL TLS protocol versions detected:
      SSLv3:   no
      SSLv23:  no
      TLSv1.0: no
      TLSv1.1: no
      TLSv1.2: no
      TLS flx: no
  If I add "LIBS=-lcrypto", it will support, I see the config.log, you add -lssl in check them(SSLv3,SSLv23 ...),but not add -lcrypto,  so I must add it , and no datesheet about how to support ssl,.
     So, I didn't konw I am right or wrong, please tell me.

**Comment by francisbrosnan** [comment]
Hello,

This is not an issue of noPoll, but how you get it compiled with OpenSSL using
a non-standard location (usually located at ${prefix}/openssl/ssl.h). Too specific. 

To better know what OpenSSL options you have to pass to LIBS or CFLAGS, check OpenSSL's
documentation or your distro's doc. However, they might be even wrong because your
are using an OpenSSL located in a very non-standard folder which indicates that 
OpenSSL build is custom-made which might not need "-lssl -lcrypto" but just "-lssl"....or
any other option...

That is, very specific for your case. Thanks for reporting,
Regards,
